DROP TABLE IF EXISTS users;

CREATE TABLE users
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	NAME VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	PRIMARY KEY (id)
);




DROP TABLE IF EXISTS orders;

CREATE TABLE orders
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	number VARCHAR(30) NULL DEFAULT NULL COMMENT '订单编号',
	PRIMARY KEY (id)
);
